### ISSUE TITLE
Not really an issue: requesting your list of arduino libraries which require installing for balancing projects

### ISSUE THREAD

**Issue by Smitty-44** [remrc/One-Axis-Reaction-Wheel-Stick#1]
Hi there,
Really enjoyed viewing your balancing projects and I hope to recreate the balancing sticks.
I am currently in process of acquiring the required hardware.
I downloaded the programs as well.
I was hoping you had a list of arduino libraries you used for these projects.
I apologize if you have them listed somewhere and I overlooked them.
When you get a minute, could you specify a list?
Thank you in advance,
Jay

**Comment by remrc** [comment]
In this project - none. 
Two axis - pwm library is required. https://github.com/terryjmyers/PWM. I don't remember, maybe it built-in.

**Comment by Smitty-44** [comment]
> In this project - none. Two axis - pwm library is required. https://github.com/terryjmyers/PWM. I don't remember, maybe it built-in.

Hi there, thanks for the quick response.
There is a AVR_PWM in the library manager which is available in the IDE.
Is that ok, too?
Thanks again, 
Jay
